### ISSUE TITLE
遇到找不到iconfont_builder命令时解决方法

### ISSUE THREAD

**Issue by lifetin** [ymzuiku/iconfont_builder#1]
![44](https://user-images.githubusercontent.com/10474968/59290182-8e39ea80-8caa-11e9-95fa-a9ffcb74793e.png)
踩坑.
照方法执行安装后,结果说找不到命令.原因是没有把目录加入到环境变量中.
将下面的路径加环境变量,重运行cmd,即可
C:\Users\Administrator\AppData\Roaming\Pub\Cache\bin\

![55](https://user-images.githubusercontent.com/10474968/59290253-b6294e00-8caa-11e9-8f2c-f2ffc814900a.png)

**Comment by lifetin** [comment]
望补充一下相关说明

**Comment by ymzuiku** [comment]
谢谢，平时没有windows，能不能帮忙提一个pr，在README中添加这个说明呢？
