### ISSUE TITLE
解析iconfont下载的字体文件时,在源码中没有最后一个图标, 稳定重现.

### ISSUE THREAD

**Issue by NetFly-VPN** [ymzuiku/iconfont_builder#2]
用最新把的Iconfont 生成附件中的字体, 最后一个图标一直导不出来

[Icons.zip](https://github.com/ymzuiku/iconfont_builder/files/3313990/Icons.zip)

**Comment by rdsuncn** [comment]
我也这样的

[fonts.zip](https://github.com/ymzuiku/iconfont_builder/files/3732351/fonts.zip)

**Comment by ymzuiku** [comment]
抱歉，平时忙，社区已有有人帮忙提供了pr：https://github.com/ymzuiku/iconfont_builder/pull/3
已经合并并修复此问题了；
