### ISSUE TITLE
执行 iconfont_builder --from ./fonts --to ./lib/Iconfont.dart 失败

### ISSUE THREAD

**Issue by xfy6238** [ymzuiku/iconfont_builder#4]
iconfont_builder --from ./fonts --to ./lib/Iconfont.dart
/Users/xufuyang/Developer/flutter/.pub-cache/bin/iconfont_builder: line 7: dart: command not found.

line 7 里的代码是: dart "/Users/xufuyang/Developer/flutter/.pub-cache/global_packages/iconfont_builder/bin/iconfont_builder.dart.snapshot.dart2" "$@"

当前Flutter版本是1.17.0.  不知道是我哪里出错了?

**Comment by woxihejinghao** [comment]
你这个是环境没配好吧

**Comment by Lidalu** [comment]
失败+1

> iconfont_builder --from ./fonts --to ./lib/Iconfont.dart

Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Utf8Encoder.convert (dart:convert/utf.dart:81:31)
#2      Codec.encode (dart:convert/codec.dart:23:32)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:31)
#4      logic (file:///Users//iconfont_builder-1.0.4/bin/iconfont_builder.dart:193:20)
#5      main (file:///Users/iconfont_builder-1.0.4/bin/iconfont_builder.dart:30:5)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by slowhandwc** [comment]
> 失败+1
> 
> > iconfont_builder --from ./fonts --to ./lib/Iconfont.dart
> 
> Unhandled exception:
> NoSuchMethodError: The getter 'length' was called on null.
> Receiver: null
> Tried calling: length
> #0 Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1 Utf8Encoder.convert (dart:convert/utf.dart:81:31)
> #2 Codec.encode (dart:convert/codec.dart:23:32)
> #3 _File.writeAsStringSync (dart:io/file_impl.dart:638:31)
> #4 logic (file:///Users//iconfont_builder-1.0.4/bin/iconfont_builder.dart:193:20)
> #5 main (file:///Users/iconfont_builder-1.0.4/bin/iconfont_builder.dart:30:5)
> #6 _startIsolate. (dart:isolate-patch/isolate_patch.dart:299:32)
> #7 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

失败+2

**Comment by pgfeng** [comment]
Can't load Kernel binary: Invalid kernel binary format version.
Unhandled exception:
NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Utf8Encoder.convert (dart:convert/utf.dart:79:31)
#2      Codec.encode (dart:convert/codec.dart:21:32)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:31)
#4      logic (file:///Users/pgf/.pub-cache/hosted/pub.flutter-io.cn/iconfont_builder-1.0.4/bin/iconfont_builder.dart:193:20)
#5      main (file:///Users/pgf/.pub-cache/hosted/pub.flutter-io.cn/iconfont_builder-1.0.4/bin/iconfont_builder.dart:30:5)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by pgfeng** [comment]
> 失败+1
> 
> > iconfont_builder-从./fonts-到./lib/Iconfont.dart
> 
> 未处理的异常：
> NoSuchMethodError：在null上调用了getter'length'。
> 接收方：空
> 尝试调用：长度
> ＃0 Object.noSuchMethod（dart：core-patch / object_patch.dart：53：5）
> [＃1](https://github.com/ymzuiku/iconfont_builder/issues/1) Utf8Encoder.convert（dart：convert / utf.dart：81：31）
> [＃2](https://github.com/ymzuiku/iconfont_builder/issues/2) Codec.encode （dart：convert / codec.dart：23：32）
> [＃3](https://github.com/ymzuiku/iconfont_builder/pull/3) _File.writeAsStringSync（dart：io / file_impl.dart：638：31）
> [＃4](https://github.com/ymzuiku/iconfont_builder/issues/4) 逻辑（file：///Users//iconfont_builder-1.0.4/bin /iconfont_builder.dart:193:20）＃5
> main（文件：///Users/iconfont_builder-1.0.4/bin/iconfont_builder.dart：30：5）
> ＃6 _startIsolate。（dart：isolate-patch / isolate_patch.dart：299：32）
> ＃7 _RawReceivePortImpl._handleMessage（dart：isolate-patch / isolate_patch.dart：168：12）

问题解决了，将iconfont_builder.dart中正则部分的默认的iconfont替换成你的class前缀和font Family名称。
注意下面这样的代码，将font Family替换成iconfont站点上面设置family名称就可以了。
`<span class="icon iconfont">`

**Comment by ymzuiku** [comment]
未能复现，暂时关闭
